export { BaseClientError, BaseForgeError, BaseServerError, ForgeError } from './baseForgeError';

// Client errors (4xx)
export {
  BadRequestError,
  UnauthorizedError,
  PaymentRequiredError,
  ForbiddenError,
  NotFoundError,
  MethodNotAllowedError,
  NotAcceptableError,
  ProxyAuthenticationRequiredError,
  RequestTimeoutError,
  ConflictError,
  GoneError,
  LengthRequiredError,
  PreconditionFailedError,
  PayloadTooLargeError,
  URITooLongError,
  UnsupportedMediaTypeError,
  RangeNotSatisfiableError,
  ExpectationFailedError,
  TeapotError,
  MisdirectedRequestError,
  UnprocessableEntityError,
  LockedError,
  FailedDependencyError,
  TooEarlyError,
  UpgradeRequiredError,
  PreconditionRequiredError,
  TooManyRequestsError,
  RequestHeaderFieldsTooLargeError,
  UnavailableForLegalReasonsError,
  NoResponseError,
  RetryWithError,
  BlockedByWindowsParentalControlsError,
  LegallyRestrictedError,
  RequestHeaderTooLargeError,
  SSLCertificateError,
  SSLCertificateRequiredError,
  HTTPRequestSentToHTTPSPortError,
  InvalidTokenError,
  TokenRequiredError,
  ClientClosedRequestError,
} from './clientErrors';

// Server errors (5xx)
export {
  InternalServerError,
  NotImplementedError,
  BadGatewayError,
  ServiceUnavailableError,
  GatewayTimeoutError,
  HTTPVersionNotSupportedError,
  VariantAlsoNegotiatesError,
  InsufficientStorageError,
  LoopDetectedError,
  BandwidthLimitExceededError,
  NotExtendedError,
  NetworkAuthenticationRequiredError,
} from './serverErrors';
